### ISSUE TITLE
Monthly does not actually calculate as it should

### ISSUE THREAD

**Issue by rmurrish** [oanda/py-api-trading#1]
in file api-trade-averages.py there's a comment that monthly doesn't calculate right. It's because that condition is never checked, theres an elif superseding that condition above. Both 'month' and 'minute' conditions are met when granularity[0] == 'M'

```
def getGranularitySeconds(granularity):
    if granularity[0] == 'S':
        return int(granularity[1:])
    elif granularity[0] == 'M':
        return 60*int(granularity[1:])

...

    #Monthly does not actually calculate as it should
    elif granularity[0] == 'M':
        return 60*60*24*30
```

possible fix: minutes would be followed by a number, monthly seems to stand alone as currently defined. if the len(granularity) > 1, you can assume minute, elif len(granularity) == 1, you can assume month. Exact detail depends on desired functionality.

**Comment by jmunnings** [comment]
Thanks for calling this out. We just went ahead and added an "and len(granularity) > 1" to the minute clause.
